sudo: required
dist: bionic
language: java
jdk: openjdk8
jobs:
  include:
    - name: oap-mllib
      dist: bionic
      jdk:
      - openjdk8
      cache:
        directories:
        - /opt/intel/inteloneapi
        - /opt/intel/oneapi
        - $HOME/downloads
      install:
      - # Install Spark 3.0
      - "[ -d $HOME/downloads ] || mkdir $HOME/downloads"
      - "cd $HOME/downloads && wget http://archive.apache.org/dist/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz"
      - "cd $HOME && tar -xf $HOME/downloads/spark-3.0.0-bin-hadoop2.7.tgz"
      - "export SPARK_HOME=$HOME/spark-3.0.0-bin-hadoop2.7"
      - # Install Dependencies
      - ${TRAVIS_BUILD_DIR}/oap-mllib/dev/install-build-deps-ubuntu.sh
      script:
      - cd ${TRAVIS_BUILD_DIR}/oap-mllib/mllib-dal      
      - export ONEAPI_ROOT=/opt/intel/oneapi
      - source /opt/intel/oneapi/dal/latest/env/vars.sh
      - source /opt/intel/oneapi/tbb/latest/env/vars.sh
      - source /tmp/oneCCL/build/_install/env/setvars.sh
      - ./test.sh

